### PR TITLE
add 4 players support and code refactoring

### PR DESCRIPTION
**Pull request by rcarubbi**

### CODE REVIEW

**Comment by rcarubbi** [comment]
Hi Servet, I really liked your project and wanted to contribute with it. My next steps will be build a backend in nodejs to turn it into an online multiplayer game. Please let me know what do you think. My intention is not to depreciate your work at all, actually I became a fan of your channel. Nice work! Cheers

**Comment by tarantino07** [comment]
Hi Raphael, I am really glad to see your attention. You've got full support from me. What library or framework will you be using? I've experience with socket.io. If you consider using socket.io, I could help you 🎉🎉✌️ Waiting to hear next steps from you..

**Comment by rcarubbi** [comment]
Yes, I'm going to use socket.io, you shall see something coming this week as I took some days off my work. :) 
feel free to add me to your social networks. You can find me as rcarubbi

**Comment by tarantino07** [comment]
I tried the game now, and I really shocked! It feels really good 😁 Nice work 🎉🎉🎉🎉

**Comment by rcarubbi** [comment]
there is a collision bug when you try to eat two joined apples

**Comment by rcarubbi** [comment]
Hi @servetgulnaroglu, it's in a stable state to be merged now and working with the multiplayer online feature as well

**Comment by tarantino07** [comment]
Hi Raphael, it looks nice and it is really enjoyable to play.  

I had an issue with the online version.  I don't know you fixed or not. The host could control the snake but guests couldn't.

**Pull request merged**
